# Generated by Django 5.0.4 on 2024-06-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditcard',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=255, primary_key=True, serialize=False)),
                ('time', models.FloatField(blank=True, db_column='Time', null=True)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('class_field', models.IntegerField(blank=True, db_column='Class', null=True)),
            ],
            options={
                'db_table': 'creditcard',
            },
        ),
    ]
